---
title: "COVID-19 Data"
output: html_document
---

<b>
<br/>
## COVID-19 Data and Indicators
</b>
<br/>

#### COVID-19 Data

National-level COVID-19 cases and deaths are obtained from University of Oxford's [Our World in Data](https://ourworldindata.org/coronavirus), while the subnational (administrative level 1) data are obtained from UN OCHA Humanitarian Data Exchange ([HDX](https://data.humdata.org/event/covid-19)). Note that the national and subnational-level COVID-19 data may not converge as they are from different sources and in some cases only a subset of subnational areas reports data. The dashboard also provides visualizations of COVID-19 forecasts, which are retrieved from the Imperial College London ([MRC Centre for Global Infectious Disease Analysis](https://mrc-ide.github.io/global-lmic-reports/)). 

These COVID-19 datasets (observed cases/deaths and the projected cases) are available at daily intervals and we refereshed the data monthly. The daily data are further aggregated to monthly to match the malaria-related indicators that are available at monthly time steps. In the visualizations, COVID-19 data are shown either as count or rate (cases per 1,000 populations or deaths per 100,000 populations). These incidence rates are calculated by dividing the cases with population data obtained from the [WorldPop](https://www.worldpop.org/geodata/summary?id=24798) (see Table below for data description).

<br/>

#### COVID-19 Indicators

To assess the vulnerability to COVID-19 for subnational geographic areas, we extracted a set of indicators that <b>potentially</b> contribute to determining areas that are at higher risk of COVID-19 transmission and health system overloads. These indicators and their sources are listed in the table below. 

<br/>

| Data                                               | Source                                                                  | Native resolution               | Update frequency | Desired indicator                                                                                                                                    |
|----------------------------------------------------|-------------------------------------------------------------------------|:-------------------------------:|:----------------:|------------------------------------------------------------------------------------------------------------------------------------------------------|
| Population (2019)                                  | [WorldPop](https://www.worldpop.org/geodata/summary?id=24798)                                                                | 1 km                            | Annual           | Percentage of population at specific age cohort                                                                                                      |
| Population density                                 | Provincial shapefiles + [WorldPop](https://www.worldpop.org/geodata/summary?id=24798)                                        | Mixed                           | N/A              | Calculate total population (from worldpop) per area (from shapefile)                                                                                 |
| Population mobility                                | [Google mobility](https://www.google.com/covid19/mobility/)                                                         | Admin 1 level & daily           | Monthly       | Change in mobility from baseline for each category                                                |
| Handwashing                                        | [DHS program](https://api.dhsprogram.com/#/index.html), [raw data](https://dhsprogram.com/data/) (request permissions)  | Admin 1 level                   | N/A              | <ul><li>Percent of population living in households with soap and water</li><li>Percent of population living in households where place for washing hands was observed</li></ul>	 |
| Health workforce                                  | PMI Quarterly Report                                                   | Admin 2 level & annual | Annual  | Density of health workers per 10,000 population from the last month available                                |
| New consultations (all cause) per 1,000 population | PMI Quarterly Report                                                    | Admin 2 level & monthly         | Quarterly        | The number of outpatient consultations for any reason that were reported in the district in the HMIS per 1,000 population                            |




<br/>

<b>Population</b>: WorldPop population data was aggregated to national (administrative level 0 / country-level) and subnational (administrative level 1 / province or state-level) by first overlaying the administrative boundary shapefiles to the population raster data. Any pixels' centroid that overlapped with the polygon were extracted and summed to produce national or subnational population data. This process is repeated for each age cohort (0-12 months, above 80 years old, and 5 years interval in between, i.e. 1-4 years old, 5-9 years old, 60-64 years old). We then aggregate the age cohort to produce total population and the proportion of population that are: under 5 years, 5-14 years, 15-24 years, 25-44 years, 45-64 years and over 65 years.

<b>Population mobility</b>: Google community mobility data is used as a proxy for population movement. More information about this data set can be found [here](https://support.google.com/covid19-mobility/answer/9824897?hl=en&ref_topic=9822927). Briefly, there are 6 mobility categories in the data: residential, workplaces, transit stations, grocery and pharmacy, retail and recreation, parks. The data measures the daily changes in the number of visitors (or time spent in) each of the categorized place as compared to the baseline days - defined as a 5-week period between 3 January - 6 February, 2020. To obtain mobility changes at monthly interval (so as to be consistent with the malaria data), we took the average of the daily data in the month. As noted in [Google's documentation](https://support.google.com/covid19-mobility/answer/9824897?hl=en&ref_topic=9822927), care should be taken when interpreting the mobility data as the baseline period used is limited and may not represent an 'average' or 'normal' condition (i.e may coincided with holidays in some areas and therefore the number of visitors are higher or lower). This mobility data is not available for several countries: Guinea, Sierra Leone, Liberia, Cote D'Ivoire, DRC, Ethiopia and Madagascar. In some countries, subnational (administrative level 1) data is available.

<br/>